export const MY_COLLECTIONS: any = {
    'Favorites': [
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
    ],
    'Country': [
        { id: { videoId: 'bmWLBX_M0yA' }, snippet: { title: 'Luke Combs - Fast Car' } },
        { id: { videoId: 'u9O-T7v4_vE' }, snippet: { title: 'Morgan Wallen - Last Night' } }
    ],
    'Hard': [
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: 'EsDeeKid - 4Raws' } },
    ],
    'BigXThaPlug': [
        { id: { videoId: 'eb5BVhWUE1A' }, snippet: { title: 'BigXThaPlug - I Hope You\'re Happy (feat. Darius Rucker)' } },
        { id: { videoId: 'p-4ofoKX1Gg' }, snippet: { title: 'BigXThaPlug - All The Way (feat. Bailey Zimmerman)' } },
        { id: { videoId: 'VQpmWQU5_8E' }, snippet: { title: 'BigXThaPlug - Hell At Night (feat. Ella Langley)' } },
        { id: { videoId: 'a3HpVeroFq0' }, snippet: { title: 'BigXThaPlug - Pray Hard (feat. Luke Combs)' } },
        { id: { videoId: 'fK_IxSNLF_I' }, snippet: { title: 'BigXThaPlug - Home (feat. Shaboozey)' } },
        { id: { videoId: 'o0qiPAYID1s' }, snippet: { title: 'BigXThaPlug - Long Nights (feat. Thomas Rhett)' } },
        { id: { videoId: 'QPmGzXoXYW8' }, snippet: { title: 'BigXThaPlug - Holy Ground (feat. Jessie Murph)' } },
        { id: { videoId: '2YsPP7b38K0' }, snippet: { title: 'BigXThaPlug - Take Care' } },
        { id: { videoId: 'eQAFAoyXpcw' }, snippet: { title: 'BigXThaPlug - Lost The Love' } },
        { id: { videoId: 'begbi44ZLqw' }, snippet: { title: 'BigXThaPlug - Change Me' } },
        { id: { videoId: 'a3HoLmCAwUA' }, snippet: { title: 'BigXThaPlug - Leave Me Alone' } },
        { id: { videoId: '0vl4FamxfUs' }, snippet: { title: 'BigXThaPlug - Therapy Session' } },
        { id: { videoId: 'gUTRomHXkRw' }, snippet: { title: 'BigXThaPlug - Planting Seeds' } },
        { id: { videoId: 'TNBeHlll0PE' }, snippet: { title: 'BigXThaPlug - Law & Order' } },
        { id: { videoId: '2aEs3Mv4uPw' }, snippet: { title: 'BigXThaPlug - Back On My BS' } },
        { id: { videoId: 'JVDUsaqgSq0' }, snippet: { title: 'BigXThaPlug - 2AM' } },
        { id: { videoId: 'kYzt_wtLF1U' }, snippet: { title: 'BigXThaPlug - Story of X' } },
        { id: { videoId: '3QwZjhHcLZk' }, snippet: { title: 'BigXThaPlug - The Largest' } },
        { id: { videoId: 'O3b2dbwT5qA' }, snippet: { title: 'BigXThaPlug - Mmhmm' } },
        { id: { videoId: 'W-Btg-OmcKE' }, snippet: { title: 'BigXThaPlug - Rich Off Rap' } },
        { id: { videoId: 'ZmfGEB2rGJA' }, snippet: { title: 'BigXThaPlug - They Don\'t Know' } },
        { id: { videoId: 'Z97O5zBF2W0' }, snippet: { title: 'BigXThaPlug - Climate (feat. Offset)' } },
        { id: { videoId: '5fGfUBVQ0iw' }, snippet: { title: 'BigXThaPlug - Rock and Roll' } },
        { id: { videoId: 'LvJuTsrPY_Y' }, snippet: { title: 'BigXThaPlug - Patience' } },
        { id: { videoId: 'u9AYK1ZZgec' }, snippet: { title: 'BigXthaPlug - Switched Up' } },
        { id: { videoId: 'iXi4pWO_t5c' }, snippet: { title: 'BigXthaPlug - Rush Hour' } },
        { id: { videoId: 'heReJ7eThrg' }, snippet: { title: 'BigXthaPlug - Primetime' } },
        { id: { videoId: 'hX0aI5Jz8i8' }, snippet: { title: 'BigXthaPlug - Texas' } },
        { id: { videoId: 'HC-dvVQ6m8A' }, snippet: { title: 'BigXthaPlug - Bad Bitches (feat. Ro$ama)' } },
        { id: { videoId: 'RW-epTbUCkQ' }, snippet: { title: 'BigXthaPlug - Bacc to Tha Basics' } },
        { id: { videoId: '1t77q_Dykac' }, snippet: { title: 'BigXthaPlug - Safehouse' } },
        { id: { videoId: 'wRmilfAVblw' }, snippet: { title: 'BigXthaPlug - Change' } },
        { id: { videoId: '66GELkCzvz0' }, snippet: { title: 'BigXthaPlug - Badu Flow' } },
        { id: { videoId: 'syEJHYSkH-o' }, snippet: { title: 'BigXthaPlug - I Know (feat. Sauce Walka)' } },
        { id: { videoId: '8qz_dkR2e7U' }, snippet: { title: 'BigXthaPlug - Levels' } },
        { id: { videoId: 'izaMfYCitIE' }, snippet: { title: 'BigXthaPlug - Thick (feat. Erica Banks & Tay Money)' } },
        { id: { videoId: '7PhMq1ztAm8' }, snippet: { title: 'BigXthaPlug - Dream' } },
        { id: { videoId: 'KmEtbvCzfrU' }, snippet: { title: 'BigXthaPlug - Whip It' } },
        { id: { videoId: 'DN8VnToyp70' }, snippet: { title: 'BigXthaPlug - Left Eye' } },
        { id: { videoId: '9Jl0zqBVnxU' }, snippet: { title: 'BigXthaPlug - Rap Niggas (feat. Ro$ama)' } },
        { id: { videoId: 'fLg7si7UuvU' }, snippet: { title: 'BigXthaPlug - Ends' } }
    ],
    'IHopeYoureHappy': [
        { id: { videoId: 'eb5BVhWUE1A' }, snippet: { title: 'I Hope You\'re Happy (feat. Darius Rucker)' } },
        { id: { videoId: 'p-4ofoKX1Gg' }, snippet: { title: 'All The Way (feat. Bailey Zimmerman)' } },
        { id: { videoId: 'VQpmWQU5_8E' }, snippet: { title: 'Hell At Night (feat. Ella Langley)' } },
        { id: { videoId: 'a3HpVeroFq0' }, snippet: { title: 'Pray Hard (feat. Luke Combs)' } },
        { id: { videoId: 'fK_IxSNLF_I' }, snippet: { title: 'Home (feat. Shaboozey)' } },
        { id: { videoId: 'o0qiPAYID1s' }, snippet: { title: 'Long Nights (feat. Thomas Rhett)' } },
        { id: { videoId: 'QPmGzXoXYW8' }, snippet: { title: 'Holy Ground (feat. Jessie Murph)' } },
    ],
    'TakeCare': [
        { id: { videoId: '2YsPP7b38K0' }, snippet: { title: 'Take Care' } },
        { id: { videoId: 'eQAFAoyXpcw' }, snippet: { title: 'Lost The Love' } },
        { id: { videoId: 'begbi44ZLqw' }, snippet: { title: 'Change Me' } },
        { id: { videoId: 'a3HoLmCAwUA' }, snippet: { title: 'Leave Me Alone' } },
        { id: { videoId: '0vl4FamxfUs' }, snippet: { title: 'Therapy Session' } },
        { id: { videoId: 'gUTRomHXkRw' }, snippet: { title: 'Planting Seeds' } },
        { id: { videoId: 'TNBeHlll0PE' }, snippet: { title: 'Law & Order' } },
        { id: { videoId: '2aEs3Mv4uPw' }, snippet: { title: 'Back On My BS' } },
        { id: { videoId: 'JVDUsaqgSq0' }, snippet: { title: '2AM' } },
        { id: { videoId: 'kYzt_wtLF1U' }, snippet: { title: 'Story of X' } },
        { id: { videoId: '3QwZjhHcLZk' }, snippet: { title: 'The Largest' } },
        { id: { videoId: 'O3b2dbwT5qA' }, snippet: { title: 'Mmhmm' } },
        { id: { videoId: 'W-Btg-OmcKE' }, snippet: { title: 'Rich Off Rap' } },
        { id: { videoId: 'ZmfGEB2rGJA' }, snippet: { title: 'They Don\'t Know' } },
    ],
    'TheBiggest': [
        { id: { videoId: 'Z97O5zBF2W0' }, snippet: { title: 'Climate (feat. Offset)' } },
        { id: { videoId: '5fGfUBVQ0iw' }, snippet: { title: 'Rock and Roll' } },
        { id: { videoId: 'LvJuTsrPY_Y' }, snippet: { title: 'Patience' } },
    ],
    'Amar': [
        { id: { videoId: 'u9AYK1ZZgec' }, snippet: { title: 'Switched Up' } },
        { id: { videoId: 'iXi4pWO_t5c' }, snippet: { title: 'Rush Hour' } },
        { id: { videoId: 'heReJ7eThrg' }, snippet: { title: 'Primetime' } },
        { id: { videoId: 'hX0aI5Jz8i8' }, snippet: { title: 'Texas' } },
        { id: { videoId: 'HC-dvVQ6m8A' }, snippet: { title: 'Bad Bitches (feat. Ro$ama)' } },
        { id: { videoId: 'RW-epTbUCkQ' }, snippet: { title: 'Bacc to Tha Basics' } },
        { id: { videoId: '1t77q_Dykac' }, snippet: { title: 'Safehouse' } },
        { id: { videoId: 'wRmilfAVblw' }, snippet: { title: 'Change' } },
        { id: { videoId: '66GELkCzvz0' }, snippet: { title: 'Badu Flow' } },
        { id: { videoId: 'syEJHYSkH-o' }, snippet: { title: 'I Know (feat. Sauce Walka)' } },
        { id: { videoId: '8qz_dkR2e7U' }, snippet: { title: 'Levels' } },
        { id: { videoId: 'izaMfYCitIE' }, snippet: { title: 'Thick (feat. Erica Banks & Tay Money)' } },
        { id: { videoId: '7PhMq1ztAm8' }, snippet: { title: 'Dream' } },
        { id: { videoId: 'KmEtbvCzfrU' }, snippet: { title: 'Whip It' } },
        { id: { videoId: 'DN8VnToyp70' }, snippet: { title: 'Left Eye' } },
        { id: { videoId: '9Jl0zqBVnxU' }, snippet: { title: 'Rap Niggas (feat. Ro$ama)' } },
        { id: { videoId: 'fLg7si7UuvU' }, snippet: { title: 'Ends' } }
    ],
    'CollegeDropout': [
        { id: { videoId: 'OTZzjAU0Kg0' }, snippet: { title: 'Intro' } },
        { id: { videoId: '0Tdpq3FRGhY' }, snippet: { title: 'We Don\'t Care' } },
        { id: { videoId: 'tbmNuB7spmA' }, snippet: { title: 'Graduation Day' } },
        { id: { videoId: 'uHcP8XX5IJA' }, snippet: { title: 'All Falls Down (ft. Syleena Johnson)' } },
        { id: { videoId: 'psb2dFToHLA' }, snippet: { title: 'I\'ll Fly Away' } },
        { id: { videoId: 'mn77gzjBl1U' }, snippet: { title: 'Spaceship (ft. Consequence & GLC)' } },
        { id: { videoId: '1fpkdSfPzio' }, snippet: { title: 'Jesus Walks' } },
        { id: { videoId: 'p4NvOKy7GOU' }, snippet: { title: 'Never Let Me Down (ft. JAY-Z & J. Ivy)' } },
        { id: { videoId: 'UHpaLbhk8vM' }, snippet: { title: 'Get Em High (ft. Common & Talib Kweli)' } },
        { id: { videoId: 'hLeS2By_zPE' }, snippet: { title: 'Workout Plan' } },
        { id: { videoId: 'IzNunT2AOO4' }, snippet: { title: 'The New Workout Plan' } },
        { id: { videoId: 'pwkYUhePecQ' }, snippet: { title: 'Slow Jamz' } },
        { id: { videoId: 'E3dWKq3s6u0' }, snippet: { title: 'Breathe In Breathe Out (ft. Ludacris)' } },
        { id: { videoId: 'g9xopViBKOQ' }, snippet: { title: 'School Spirit Skit 1' } },
        { id: { videoId: '-MOIPnu50O4' }, snippet: { title: 'School Spirit' } },
        { id: { videoId: '7xL9VLARq8k' }, snippet: { title: 'School Spirit Skit 2' } },
        { id: { videoId: 'ufN8MxyMlEQ' }, snippet: { title: 'Lil Jimmy Skit' } },
        { id: { videoId: 'cgo2IKS4inU' }, snippet: { title: 'Two Words' } },
        { id: { videoId: 'AE8y25CcE6s' }, snippet: { title: 'Through The Wire' } },
        { id: { videoId: 'JwAjANmjajc' }, snippet: { title: 'Family Business' } },
        { id: { videoId: 'cpbeS15sHZ0' }, snippet: { title: 'Last Call' } }
    ],
    'LateRegistration': [
        { id: { videoId: '14Ef5mb2qhc' }, snippet: { title: 'Wake Up Mr. West' } },
        { id: { videoId: 'lRpeSw_2egU' }, snippet: { title: 'Heard \'Em Say (ft. Adam Levine)' } },
        { id: { videoId: 'sEXKgJv3HYM' }, snippet: { title: 'Touch the Sky (ft. Lupe Fiasco)' } },
        { id: { videoId: 'odAfBDPC6lU' }, snippet: { title: 'Gold Digger (ft. Jamie Foxx)' } },
        { id: { videoId: 'TqrI_FZsMn8' }, snippet: { title: 'Skit #1' } },
        { id: { videoId: 'snUi2gsbWZc' }, snippet: { title: 'Drive Slow (ft. Paul Wall & GLC)' } },
        { id: { videoId: '9HMrXIshVHw' }, snippet: { title: 'My Way Home (ft. Common)' } },
        { id: { videoId: 'X5bjOKxttlo' }, snippet: { title: 'Crack Music (ft. The Game)' } },
        { id: { videoId: 'ONo9rAmFGs0' }, snippet: { title: 'Roses' } },
        { id: { videoId: '0Zz4WcJ1TN4' }, snippet: { title: 'Bring Me Down (ft. Brandy)' } },
        { id: { videoId: 'l2YKiAaV-kA' }, snippet: { title: 'Addiction' } },
        { id: { videoId: 'QD1jFxZKsC0' }, snippet: { title: 'Skit #2' } },
        { id: { videoId: 'FhCUCAO1ZFo' }, snippet: { title: 'Diamonds From Sierra Leone (Remix) (ft. JAY-Z)' } },
        { id: { videoId: 'CE4Lck4GLCM' }, snippet: { title: 'We Major (ft. Nas & Really Doe)' } },
        { id: { videoId: 'LNxIvh6z1pk' }, snippet: { title: 'Skit #3' } },
        { id: { videoId: 'mVzA-xrqVe4' }, snippet: { title: 'Hey Mama' } },
        { id: { videoId: 'qy5ESJN6RtY' }, snippet: { title: 'Celebration' } },
        { id: { videoId: 'wpwcq3KFg8Q' }, snippet: { title: 'Skit #4' } },
        { id: { videoId: 'MQqCcaXFuvw' }, snippet: { title: 'Gone (ft. Cam\'ron & Consequence)' } },
        { id: { videoId: 'kSpG995BbqU' }, snippet: { title: 'Diamonds from Sierra Leone' } },
        { id: { videoId: 'Vmb5WKN4zZM' }, snippet: { title: 'Late' } }
    ],
    'Graduation': [
        { id: { videoId: 'WwYbTxOZF0k' }, snippet: { title: 'Good Morning' } },
        { id: { videoId: 'jKT4ArZCkso' }, snippet: { title: 'Champion' } },
        { id: { videoId: '2ulp_AMut14' }, snippet: { title: 'Stronger' } },
        { id: { videoId: 'MxEjnYdfLXU' }, snippet: { title: 'I Wonder' } },
        { id: { videoId: 'GTmbyuTKT_c' }, snippet: { title: 'Good Life (ft. T-Pain)' } },
        { id: { videoId: 'hqvcww4ydh8' }, snippet: { title: 'Can\'t Tell Me Nothing' } },
        { id: { videoId: 'LYa5q2AjWNQ' }, snippet: { title: 'Barry Bonds (ft. Lil Wayne)' } },
        { id: { videoId: '9uOg6LyIAUo' }, snippet: { title: 'Drunk and Hot Girls (ft. Yasiin Bey)' } },
        { id: { videoId: 'cxKs2b5lRsA' }, snippet: { title: 'Flashing Lights (ft. Dwele)' } },
        { id: { videoId: 'ZtkNfC5Oymw' }, snippet: { title: 'Everything I Am (ft. DJ Premier)' } },
        { id: { videoId: 'e-IAGmTuUmw' }, snippet: { title: 'The Glory' } },
        { id: { videoId: 'YOzAdMs5dEc' }, snippet: { title: 'Homecoming (ft. Chris Martin)' } },
        { id: { videoId: 'HInIGGXhJHs' }, snippet: { title: 'Big Brother' } },
        { id: { videoId: '_J-OaFVdTKE' }, snippet: { title: 'Good Night (ft. Al Be Back & Yasiin Bey)' } },
        { id: { videoId: 'rHlRTg1hvoc' }, snippet: { title: 'Bittersweet Poetry (ft. John Mayer)' } }
    ],
    '808sHeartbreak': [
        { id: { videoId: 'd9BMPmfxaoM' }, snippet: { title: 'Say You Will' } },
        { id: { videoId: 'tX3IvpH6loc' }, snippet: { title: 'Welcome To Heartbreak (ft. Kid Cudi)' } },
        { id: { videoId: 's40BTpfAELs' }, snippet: { title: 'Heartless' } },
        { id: { videoId: 'KaumK4b6DqQ' }, snippet: { title: 'Amazing (ft. Young Jeezy)' } },
        { id: { videoId: 'ek_T6atbfe0' }, snippet: { title: 'Love Lockdown' } },
        { id: { videoId: 'CiY8-LYkCEk' }, snippet: { title: 'Paranoid (ft. Mr Hudson)' } },
        { id: { videoId: 'kVl__NgDAdw' }, snippet: { title: 'RoboCop' } },
        { id: { videoId: 'TUfuDKKGQxU' }, snippet: { title: 'Street Lights' } },
        { id: { videoId: '1BlH1JZBeXI' }, snippet: { title: 'Bad News' } },
        { id: { videoId: 'T5e-nhk4HTQ' }, snippet: { title: 'See You In My Nightmares (ft. Lil Wayne)' } },
        { id: { videoId: 'tpT7H7qIHIo' }, snippet: { title: 'Coldest Winter' } },
        { id: { videoId: 'OeCdG0Mzrkw' }, snippet: { title: 'Pinocchio Story (Live From Singapore)' } }
    ],
    'MBDTF': [
        { id: { videoId: 'UTH1VNHLjng' }, snippet: { title: 'Dark Fantasy' } },
        { id: { videoId: 'miJAfs7jhak' }, snippet: { title: 'Gorgeous (ft. Kid Cudi & Raekwon)' } },
        { id: { videoId: 'k8JflBNovLE' }, snippet: { title: 'POWER' } },
        { id: { videoId: 'WHxRd_va950' }, snippet: { title: 'All of the Lights (Interlude)' } },
        { id: { videoId: 'DTq4XEliPag' }, snippet: { title: 'All of the Lights' } },
        { id: { videoId: 'pS6HRKZQLFA' }, snippet: { title: 'Monster (ft. JAY-Z, Rick Ross, Nicki Minaj & Bon Iver)' } },
        { id: { videoId: '0o9HzQ3zAcE' }, snippet: { title: 'So Appalled (ft. JAY-Z, Pusha T, Ludacris, Swizz Beatz & CyHi The Prynce)' } },
        { id: { videoId: 'sk3rpYkiHe8' }, snippet: { title: 'Devil In a New Dress (ft. Rick Ross)' } },
        { id: { videoId: 'VhEoCOWUtcU' }, snippet: { title: 'Runaway (ft. Pusha T)' } },
        { id: { videoId: 'tJKNcI6jC6A' }, snippet: { title: 'Hell of a Life' } },
        { id: { videoId: '6mp72xUirfs' }, snippet: { title: 'Blame Game (ft. John Legend)' } },
        { id: { videoId: '1nawiZsuFI8' }, snippet: { title: 'Lost In the World (ft. Bon Iver)' } },
        { id: { videoId: 'UB6sXiZ1ldw' }, snippet: { title: 'Who Will Survive In America' } },
        { id: { videoId: '-5pIEDvec0g' }, snippet: { title: 'See Me Now (ft. Beyoncé, Big Sean & Charlie Wilson)' } }
    ],
    'WatchTheThrone': [
        { id: { videoId: 'M37VucWh06Y' }, snippet: { title: 'No Church in the Wild (ft. Frank Ocean & The-Dream)' } },
        { id: { videoId: 'aL3XdCn5OsE' }, snippet: { title: 'Lift Off (ft. Beyoncé)' } },
        { id: { videoId: 'fbFnF-86eYs' }, snippet: { title: 'Niggas in Paris' } },
        { id: { videoId: '1mcSLB9T1SQ' }, snippet: { title: 'Otis (ft. Otis Redding)' } },
        { id: { videoId: 'Hx33HSpYKmI' }, snippet: { title: 'Gotta Have It' } },
        { id: { videoId: 'ySe94vmeGwk' }, snippet: { title: 'New Day' } },
        { id: { videoId: 'S6jhi0AHtyM' }, snippet: { title: 'That\'s My Bitch' } },
        { id: { videoId: 'mx34fi1dodU' }, snippet: { title: 'Welcome to the Jungle' } },
        { id: { videoId: 'P1_zcreGgr8' }, snippet: { title: 'Who Gon Stop Me' } },
        { id: { videoId: '54OtJlwazGo' }, snippet: { title: 'Murder to Excellence' } },
        { id: { videoId: 'YvQzg_jKPXk' }, snippet: { title: 'Made in America (ft. Frank Ocean)' } },
        { id: { videoId: 'HVD4lnfz0-M' }, snippet: { title: 'Why I Love You (ft. Mr Hudson)' } },
        { id: { videoId: 'bOZvReh7kQU' }, snippet: { title: 'Illest Motherfucker Alive' } },
        { id: { videoId: 'ReNj2rb1zlI' }, snippet: { title: 'H·a·m' } },
        { id: { videoId: '50VLVosGpJw' }, snippet: { title: 'Primetime' } },
        { id: { videoId: 'nSptfC2Qmvw' }, snippet: { title: 'The Joy (ft. Curtis Mayfield)' } }
    ],
    'Yeezus': [
        { id: { videoId: 'uU9Fe-WXew4' }, snippet: { title: 'On Sight' } },
        { id: { videoId: 'LXeQ6bmV7oU' }, snippet: { title: 'Black Skinhead' } },
        { id: { videoId: 'KuQoQgL63Xo' }, snippet: { title: 'I Am a God' } },
        { id: { videoId: 'vQ0u09mFodw' }, snippet: { title: 'New Slaves' } },
        { id: { videoId: 'bvBfiRWLj_0' }, snippet: { title: 'Hold My Liquor' } },
        { id: { videoId: '_jZuz3NEr18' }, snippet: { title: 'I\'m In It' } },
        { id: { videoId: 'KEA0btSNkpw' }, snippet: { title: 'Blood On the Leaves' } },
        { id: { videoId: '5hthMeEqf40' }, snippet: { title: 'Guilt Trip' } },
        { id: { videoId: 'vUFiVwa6U_c' }, snippet: { title: 'Send It Up' } },
        { id: { videoId: '5gjKuISTMRE' }, snippet: { title: 'Bound 2' } }
    ],
    'TLOP': [
        { id: { videoId: 'S_2C0ZX0M84' }, snippet: { title: 'Ultralight Beam' } },
        { id: { videoId: '_MIsk8VoNhM' }, snippet: { title: 'Father Stretch My Hands, Pt. 1' } },
        { id: { videoId: 'V4XsK4ALZBI' }, snippet: { title: 'Pt. 2' } },
        { id: { videoId: 'iRyKLQWY9CA' }, snippet: { title: 'Famous' } },
        { id: { videoId: 'wcKkSyAip7c' }, snippet: { title: 'Feedback' } },
        { id: { videoId: '0ZqsQ9ap5_4' }, snippet: { title: 'Low Lights' } },
        { id: { videoId: 'lIIN8nE8QcU' }, snippet: { title: 'Highlights' } },
        { id: { videoId: '53n94Ihfh1c' }, snippet: { title: 'Freestyle 4' } },
        { id: { videoId: 'mUv0t2wX_AI' }, snippet: { title: 'I Love Kanye' } },
        { id: { videoId: 'Sh855LWd774' }, snippet: { title: 'Waves' } },
        { id: { videoId: 'ZvtEQ0Vm56s' }, snippet: { title: 'FML' } },
        { id: { videoId: 'AZcxZ-oiEb8' }, snippet: { title: 'Real Friends' } },
        { id: { videoId: 'OZHjWc0Ssvk' }, snippet: { title: 'Wolves' } },
        { id: { videoId: 'ToApLHZl41E' }, snippet: { title: 'Frank\'s Track' } },
        { id: { videoId: 'N8qRsbAJ_G0' }, snippet: { title: 'Siiiiiiiiilver Surffffeeeeer Intermission' } },
        { id: { videoId: 'DnyVvJqCa5s' }, snippet: { title: '30 Hours' } },
        { id: { videoId: '0F5CSjcRZxU' }, snippet: { title: 'No More Parties in LA' } },
        { id: { videoId: 'sgIOSLWAcTU' }, snippet: { title: 'Facts (Charlie Heat Version)' } },
        { id: { videoId: 'qOZ0hPp3OZU' }, snippet: { title: 'Fade' } },
        { id: { videoId: 'w9rzz4pDFwA' }, snippet: { title: 'Saint Pablo' } }
    ],
    'ye': [
        { id: { videoId: 'no1YszVVybo' }, snippet: { title: 'I Thought About Killing You' } },
        { id: { videoId: 'kPPyUO6m3-4' }, snippet: { title: 'Yikes' } },
        { id: { videoId: 'YdA7swZoxks' }, snippet: { title: 'All Mine' } },
        { id: { videoId: '46CQiDFtu3s' }, snippet: { title: 'Wouldn\'t Leave (ft. PARTYNEXTDOOR)' } },
        { id: { videoId: 'Ir7uoqfocPg' }, snippet: { title: 'No Mistakes' } },
        { id: { videoId: 'qAsHVwl-MU4' }, snippet: { title: 'Ghost Town (ft. 070 Shake)' } },
        { id: { videoId: 'pOLMGTtphCc' }, snippet: { title: 'Violent Crimes' } }
    ],
    'JesusIsKing': [
        { id: { videoId: 'T58tRXzjC7c' }, snippet: { title: 'Every Hour (ft. Sunday Service Choir)' } },
        { id: { videoId: '6CNPg2IQoC0' }, snippet: { title: 'Selah' } },
        { id: { videoId: 'J8iXDK0K95o' }, snippet: { title: 'Follow God' } },
        { id: { videoId: 'Lp0q1wWe6XI' }, snippet: { title: 'Closed on Sunday' } },
        { id: { videoId: 'AOBQkHy8_p8' }, snippet: { title: 'On God' } },
        { id: { videoId: 'Mrfu0FBB110' }, snippet: { title: 'Everything We Need (ft. Ant Clemons & Ty Dolla $ign)' } },
        { id: { videoId: '-YfG1Xbo4OA' }, snippet: { title: 'Water (ft. Ant Clemons)' } },
        { id: { videoId: 'G8u3P7Xqlvo' }, snippet: { title: 'God Is' } },
        { id: { videoId: 'dojATOk1GHA' }, snippet: { title: 'Hands On (ft. Fred Hammond)' } },
        { id: { videoId: '8yQVcGkbpAc' }, snippet: { title: 'Use This Gospel (ft. Clipse & Kenny G)' } },
        { id: { videoId: 'rns_n82HiMo' }, snippet: { title: 'Jesus Is Lord' } }
    ],
    'DondaDeluxe': [
        { id: { videoId: 'J8k-73s2fHw' }, snippet: { title: 'Donda Chant' } },
        { id: { videoId: 'gVNTAZKLe40' }, snippet: { title: 'Hurricane' } },
        { id: { videoId: 'NGywD7LVnGY' }, snippet: { title: 'Moon' } },
        { id: { videoId: '7YNL5DCRNec' }, snippet: { title: 'Life Of The Party' } },
        { id: { videoId: 'xvuzWi_l-U8' }, snippet: { title: 'Off The Grid' } },
        { id: { videoId: '2n89HaWYrxo' }, snippet: { title: 'Jail' } },
        { id: { videoId: 'fc8-lG6Wnus' }, snippet: { title: 'Praise God' } },
        { id: { videoId: 'kVQu2ZGDdyw' }, snippet: { title: 'Come to Life (Deluxe)' } },
        { id: { videoId: '6H4nv7CStps' }, snippet: { title: 'Believe What I Say' } },
        { id: { videoId: '63aPcK6CXyA' }, snippet: { title: 'No Child Left Behind' } },
        { id: { videoId: 'NcH7gveMJ1o' }, snippet: { title: 'Up From The Ashes' } },
        { id: { videoId: 'IsYOlnRNfiM' }, snippet: { title: 'Remote Control pt 2' } },
        { id: { videoId: 'au0wGht4h7s' }, snippet: { title: 'God Breathed' } },
        { id: { videoId: 'svdR1x7i29E' }, snippet: { title: 'Lord I Need You' } },
        { id: { videoId: 'XhvSHlvLOvc' }, snippet: { title: '24' } },
        { id: { videoId: 'EllP62ixGoQ' }, snippet: { title: 'Junya' } },
        { id: { videoId: 'GKuVipCSp_A' }, snippet: { title: 'Never Abandon Your Family' } },
        { id: { videoId: 'RFAKl20eBIk' }, snippet: { title: 'Donda' } },
        { id: { videoId: 'mx42ZdRXneI' }, snippet: { title: 'Keep My Spirit Alive' } },
        { id: { videoId: '-AzhiF13orE' }, snippet: { title: 'Jesus Lord pt 2' } },
        { id: { videoId: 'Vn0soMSMBbg' }, snippet: { title: 'Heaven and Hell' } },
        { id: { videoId: 'k7lWHbuTe0Y' }, snippet: { title: 'Remote Control' } },
        { id: { videoId: 'abacwIkMvOM' }, snippet: { title: 'Tell The Vision' } },
        { id: { videoId: '1ZroKhSYF08' }, snippet: { title: 'Jonah' } },
        { id: { videoId: 'lIJ-6JTVi0Q' }, snippet: { title: 'Pure Souls' } },
        { id: { videoId: 'xhWXPchSNUE' }, snippet: { title: 'Ok Ok' } },
        { id: { videoId: 'ypBQ6GjOLi0' }, snippet: { title: 'New Again' } },
        { id: { videoId: 'MUsT3IwuAaU' }, snippet: { title: 'Jesus Lord' } },
        { id: { videoId: 'Mrv4E2xNwuM' }, snippet: { title: 'Ok Ok pt 2' } },
        { id: { videoId: 'abI6-8mPyyk' }, snippet: { title: 'Junya pt 2' } },
        { id: { videoId: 'uaOG8roHTX4' }, snippet: { title: 'Jail, Pt. 2' } },
        { id: { videoId: 'Fe8IKAJxZ_g' }, snippet: { title: 'Keep My Spirit Alive pt 2' } }
    ],
    '3Pete': [
        { id: { videoId: '_DkPOeT8Rxo' }, snippet: { title: '3Pete - DNA' } },
        { id: { videoId: '0Ns36QwDHX8' }, snippet: { title: '3Pete - Clip Farmer' } },
        { id: { videoId: 'Bt_iYAiaWVk' }, snippet: { title: '3Pete - On The Run' } },
        { id: { videoId: 'KbVPIQnXzhE' }, snippet: { title: '3Pete - All Night' } },
        { id: { videoId: 'yQ1NfM7oKj0' }, snippet: { title: '3Pete - Get Lost' } }
    ],
    'Rebel': [
        { id: { videoId: 'gt_Oe2yGE4o' }, snippet: { title: '4 Raws' } },
        { id: { videoId: 'Q5nACsDOkNA' }, snippet: { title: 'Cali Man (ft. Rico Ace)' } },
        { id: { videoId: 'cfeg_fv5H2g' }, snippet: { title: 'Prague' } },
        { id: { videoId: 'OXZzIIg9RFA' }, snippet: { title: 'Dirty' } },
        { id: { videoId: 'OGLZg4t7g4I' }, snippet: { title: 'LV Sandals (ft. fakemink & Rico Ace)' } },
        { id: { videoId: 'b1Nvm8AK0pY' }, snippet: { title: 'Panic' } },
        { id: { videoId: 'ookD4DXQ_28' }, snippet: { title: '5am (ft. Fimiguerrero)' } },
        { id: { videoId: 'rC12fv_GwCI' }, snippet: { title: 'Phantom (ft. Rico Ace)' } },
        { id: { videoId: 'kK0Vd3daL_o' }, snippet: { title: 'Mist (ft. Rico Ace)' } },
        { id: { videoId: 'dddCZfURcko' }, snippet: { title: 'Rottweiler' } },
        { id: { videoId: 'hs57himZrfc' }, snippet: { title: 'Tartan (ft. Fimiguerrero)' } }
    ]
};